export default {
  arrowParens: 'always',
  importOrder: [
    '^react$',
    '// Third party modules',
    '<THIRD_PARTY_MODULES>',
    '',
    '^@/(.*)$',
    '^[./]',
    '',
    '<TYPES>^(node:)',
    '<TYPES>',
    '<TYPES>^[.]',
  ],
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  importOrderSeparation: true,
  importOrderTypeScriptVersion: '5.0.0',
  jsxSingleQuote: true,
  plugins: ['prettier-plugin-organize-imports', '@ianvs/prettier-plugin-sort-imports'],
  printWidth: 120,
  semi: true,
  singleAttributePerLine: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
};
